language: php
php:
  - 5.6
  - hhvm

branches:
  only:
    - master
    - develop

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.travis .env

script:
  - php artisan key:generate 
  - phpunit